# This is our first CI/CD pipeline!
# It will run every time we push code or create a pull request

name: CI Pipeline

# When should this pipeline run?
on:
  push:
    branches: [ main, develop ]  # Run on pushes to main or develop
  pull_request:
    branches: [ main ]           # Run on PRs to main

# What version of .NET should we use?
env:
  DOTNET_VERSION: '8.0.x'

# Define the jobs (steps) that should run
jobs:
  # Job 1: Build and Test
  build-and-test:
    name: 'Build and Test'
    runs-on: ubuntu-latest      # Use Ubuntu (faster and cheaper than Windows)
    
    steps:
    # Step 1: Get our code
    - name: 'Checkout code'
      uses: actions/checkout@v4
    
    # Step 2: Install .NET
    - name: 'Setup .NET'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    # Step 3: Restore packages (like npm install for .NET)
    - name: 'Restore dependencies'
      run: dotnet restore
    
    # Step 4: Build the code
    - name: 'Build'
      run: dotnet build --configuration Release --no-restore
    
    # Step 5: Run tests
    - name: 'Run tests'
      run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage"
    
    # Step 6: Upload test results (optional but helpful)
    - name: 'Upload test results'
      uses: actions/upload-artifact@v4
      if: always()              # Upload even if tests fail
      with:
        name: test-results
        path: '**/TestResults/**'