# Deployment Pipeline - Only runs when CI passes
name: Deploy

on:
  push:
    branches: [ main ]  # Only deploy from main branch

env:
  DOTNET_VERSION: '8.0.x'
  AZURE_WEBAPP_NAME: 'my-test-api'  # Change this to your app name

jobs:
  deploy:
    name: 'Deploy to Azure'
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v4
    
    - name: 'Setup .NET'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: 'Restore dependencies'
      run: dotnet restore
    
    - name: 'Build for production'
      run: dotnet build --configuration Release --no-restore
    
    - name: 'Publish app'
      run: dotnet publish src/TestApi/TestApi.csproj --configuration Release --output ./publish
    
    # This step would deploy to Azure (commented out for safety)
    # - name: 'Deploy to Azure Web App'
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
    #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    #     package: ./publish
    
    - name: 'Upload deployment package'
      uses: actions/upload-artifact@v4
      with:
        name: deployment-package
        path: ./publish